"""schema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 20:59:27.598015
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_igreja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_igreja', sa.String(length=120), nullable=True),
    sa.Column('nome_app', sa.String(length=15), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True, comment='#rrggbb'),
    sa.Column('logo_versao', sa.Integer(), nullable=True, comment='Muda a cada upload (cache dos ícones); nulo = sem logo'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trimestres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False, comment='1 a 4 (trimestres do ano)'),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('numero BETWEEN 1 AND 4', name='ck_trimestre_numero'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'numero', name='uq_trimestre_ano_numero')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('faixa_etaria', sa.String(length=60), nullable=False, comment='Adultos, Jovens, Adolescentes, Juniores, Primários, Maternal, etc.'),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('domingos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trimestre_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False, comment='Número sequencial do domingo dentro do trimestre (1º, 2º, …)'),
    sa.Column('tema_licao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['trimestre_id'], ['trimestres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trimestre_id', 'data', name='uq_domingo_trim_data'),
    sa.UniqueConstraint('trimestre_id', 'numero', name='uq_domingo_trim_numero')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('trimestre_id', sa.Integer(), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trimestre_id'], ['trimestres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'turma_id', 'trimestre_id', name='uq_matricula_aluno_turma_trim')
    )
    op.create_table('turmas_professores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('trimestre_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=60), nullable=False, comment='Professor Titular, Auxiliar, Secretário(a), etc.'),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trimestre_id'], ['trimestres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turma_id', 'professor_id', 'trimestre_id', name='uq_turma_prof_trim')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='admin | professor'),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chamadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domingo_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('nome_visitante', sa.String(length=200), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('trouxe_biblia', sa.Boolean(), nullable=False),
    sa.Column('trouxe_revista', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.CheckConstraint('(aluno_id IS NOT NULL AND nome_visitante IS NULL) OR (aluno_id IS NULL AND nome_visitante IS NOT NULL)', name='ck_chamada_aluno_ou_visitante'),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domingo_id'], ['domingos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domingo_id', 'turma_id', 'aluno_id', name='uq_chamada_aluno')
    )
    op.create_table('fechamentos_domingo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domingo_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('total_matriculados', sa.Integer(), nullable=False),
    sa.Column('total_presentes', sa.Integer(), nullable=False),
    sa.Column('total_visitantes', sa.Integer(), nullable=False),
    sa.Column('total_ausentes', sa.Integer(), nullable=False),
    sa.Column('total_biblias', sa.Integer(), nullable=False),
    sa.Column('total_revistas', sa.Integer(), nullable=False),
    sa.Column('valor_ofertas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domingo_id'], ['domingos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domingo_id', 'turma_id', name='uq_fechamento_dom_turma')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domingo_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False, comment='Dízimo, Oferta, Missionária, etc.'),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domingo_id'], ['domingos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes_troca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_origem_id', sa.Integer(), nullable=False),
    sa.Column('turma_destino_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pendente | aprovada | recusada | cancelada'),
    sa.Column('resposta', sa.Text(), nullable=True, comment='Observação do admin ao decidir'),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('decidido_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_destino_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_origem_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_troca_status', 'solicitacoes_troca', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_troca_status', table_name='solicitacoes_troca')
    op.drop_table('solicitacoes_troca')
    op.drop_table('ofertas')
    op.drop_table('fechamentos_domingo')
    op.drop_table('chamadas')
    op.drop_table('usuarios')
    op.drop_table('turmas_professores')
    op.drop_table('matriculas')
    op.drop_table('domingos')
    op.drop_table('turmas')
    op.drop_table('trimestres')
    op.drop_table('professores')
    op.drop_table('configuracao_igreja')
    op.drop_table('alunos')
    # ### end Alembic commands ###
